version: "3.9"
services:
    webapp:
        container_name: media_librarian_webapp
        hostname: webapp
        build: ./docker/local
        env_file: ./src/.env
        ports:
            - "192.168.240.9:80:80"
        volumes:
            - ./src:/app
            - ./logs:/logs
        depends_on:
            - pgsql
        networks:
            - media_librarian_network
        command: [ "webapp" ]
        logging:
            driver: json-file
            options:
                max-size: "128m"
                max-file: "1"
    pgsql:
        container_name: media_librarian_db
        image: postgres:14-alpine
        ports:
            - "192.168.240.9:5432:5432"
        volumes:
            - ./pgsql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "${DB_DATABASE:?}"
            POSTGRES_USER: "${DB_USERNAME:?}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:?}"
        networks:
            - media_librarian_network
        healthcheck:
            test: [ "CMD", "pg_isready -q -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
networks:
    media_librarian_network:
        driver: bridge
