/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as PasswordResetRouteImport } from './routes/password-reset';
import { Route as LoginRouteImport } from './routes/login';
import { Route as EmailConfirmationRouteImport } from './routes/email-confirmation';
import { Route as AppRouteImport } from './routes/app';
import { Route as IndexRouteImport } from './routes/index';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const EmailConfirmationRoute = EmailConfirmationRouteImport.update({
  id: '/email-confirmation',
  path: '/email-confirmation',
  getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/app': typeof AppRoute;
  '/email-confirmation': typeof EmailConfirmationRoute;
  '/login': typeof LoginRoute;
  '/password-reset': typeof PasswordResetRoute;
  '/profile': typeof ProfileRoute;
  '/signup': typeof SignupRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/app': typeof AppRoute;
  '/email-confirmation': typeof EmailConfirmationRoute;
  '/login': typeof LoginRoute;
  '/password-reset': typeof PasswordResetRoute;
  '/profile': typeof ProfileRoute;
  '/signup': typeof SignupRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/app': typeof AppRoute;
  '/email-confirmation': typeof EmailConfirmationRoute;
  '/login': typeof LoginRoute;
  '/password-reset': typeof PasswordResetRoute;
  '/profile': typeof ProfileRoute;
  '/signup': typeof SignupRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/app'
    | '/email-confirmation'
    | '/login'
    | '/password-reset'
    | '/profile'
    | '/signup';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/app'
    | '/email-confirmation'
    | '/login'
    | '/password-reset'
    | '/profile'
    | '/signup';
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/email-confirmation'
    | '/login'
    | '/password-reset'
    | '/profile'
    | '/signup';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRoute: typeof AppRoute;
  EmailConfirmationRoute: typeof EmailConfirmationRoute;
  LoginRoute: typeof LoginRoute;
  PasswordResetRoute: typeof PasswordResetRoute;
  ProfileRoute: typeof ProfileRoute;
  SignupRoute: typeof SignupRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/password-reset': {
      id: '/password-reset';
      path: '/password-reset';
      fullPath: '/password-reset';
      preLoaderRoute: typeof PasswordResetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/email-confirmation': {
      id: '/email-confirmation';
      path: '/email-confirmation';
      fullPath: '/email-confirmation';
      preLoaderRoute: typeof EmailConfirmationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/app': {
      id: '/app';
      path: '/app';
      fullPath: '/app';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  EmailConfirmationRoute: EmailConfirmationRoute,
  LoginRoute: LoginRoute,
  PasswordResetRoute: PasswordResetRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
