<?php
/** @noinspection SpellCheckingInspection */

namespace App\Http\Controllers\Api;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use OpenApi\Attributes as OA;

#[OA\Info(
    version: 1,
    description: "---\n### About Rate Limiters\n\n" .
    "Endpoints may have different limits and the specific limits should be specified in the endpoint's description, " .
    "if applicable.\\\nIf not described, the default rate limiter is 60 requests per minute. " .
    "Information about limits is additionally provided with response headers:\n\n" .
    "`X-RateLimit-Limit: 3` - this means overall rate limit (number of requests per timeframe)\\\n" .
    "`X-RateLimit-Remaining: 2` - this means number of requests that are available during the timeframe\\\n" .
    '`X-RateLimit-Reset: 1736013600` - this means Unix timestamp when the limits reset (e.g. 2025-01-04T18:00:00Z)' .
    "\n### About CAPTCHA-protected endpoints\n" .
    'Several endpoints are protected from flooding, spamming and different attacks by bots, so those endpoints are ' .
    'marked with **CAPTCHA-PROTECTED** label and have a very restricted rate limit (about 1 request per 6 hours). ' .
    "This doesn't mean that the client must wait 6 hours after a single request (no matter successful or not).\\\n" .
    'To overcome the rate limit it may provide a CAPTCHA verification token that could be generated by ' .
    'a widget on frontend. Currently the application has an implementation of Turnstile (by CloudFlare) that is ' .
    "compatible with hCAPTCHA and ReCaptcha by Google.\n\n" .
    "\n#### How to use it\n\n" .
    'If you need to overcome the exceeded rate limit for a protected endpoint, you have to provide CAPTCHA response ' .
    'into `cf-turnstile-response` field along with the form data. ' .
    "For example, let's take endpoint `/api/v1/user/login` as a reference. Regular request body looks like:\n" .
    "```\n{\n  \"email\": \"john.doe@example.com\",\n  \"password\": \"PasSw0rd\",\n  \"rememberMe\": true\n}\n```\n" .
    "Here is the example with CAPTCHA response provided:\\\n" .
    "```\n{\n  \"email\": \"john.doe@example.com\",\n  \"password\": \"PasSw0rd\",\n  \"rememberMe\": true,\n  " .
    '"cf-turnstile-response": "0.WoGeDojxQzHCCk023JRjfxv23olYh37jFdvPrcqmNeQ7PbSYIEuiBTK2SR_GdjfMitYEC23Gm7Vt93U1CPc' .
    'I6aIFEhG-ffe1i9e6tIfIlYCFtb7OMxTB4tKCyTdpiaA.SP5YT77nuMNdOhZlvoBWAQ.da6448d22df7dd92f56a9fcf6d7138e5ee712bcf7d0' .
    "0c281f419b3bc091cbe64\"\n" .
    "}\n```\n" .
    'When provided, this token passes server-side validation and rate limiter on the endpoint will reset for your ' .
    'client (note that the request itself takes an attempt anyway). ' .
    'If server-side validation fails, response will contain a message about CAPTCHA validation failed.' .
    "\n\nCAPTCHA token may be optionally provided even when rate limit is not exceeded, to prevent request forgery " .
    'or avoid automated requests. Then its verification will still perform and may even fail, however when ' .
    "verification succeeds, rate limit will still reset regardless of its current limit.\n\n" .
    "\n\n[Turnstile documentation (on cloudflare.com)](https://developers.cloudflare.com/turnstile/)" .
    "\n\n---\n",
    title: 'API Documentation for the Media Librarian Web App',
    contact: new OA\Contact(name: 'admin@example.com', email: 'admin@example.com'),
    license: new OA\License(name: 'Not licensed yet', identifier: 'none', url: ''),
), OA\SecurityScheme(
    securityScheme: 'BearerAuth',
    type: 'http',
    description: 'Paste your Bearer token here. You can obtain a token at the endpoint: `/api/v1/user/login`',
    name: 'api_bearer_token',
    in: 'header',
    scheme: 'bearer',
)]
#[OA\Response(
    response: 'Code204',
    description: 'No Content',
    content: new OA\MediaType(mediaType: 'application/json')
), OA\Response(
    response: 'Code401',
    description: 'Unauthorized',
    content: new OA\JsonContent(properties: [
        new OA\Property(property: 'message', type: 'string', example: '401 Authentication Required'),
    ])
), OA\Response(
    response: 'Code404',
    description: 'Not Found',
    content: new OA\JsonContent(properties: [
        new OA\Property(property: 'message', type: 'string', example: '404 Not Found'),
    ])
), OA\Response(
    response: 'Code413',
    description: 'Request Entity Too Large'
), OA\Response(
    response: 'Code422',
    description: 'Unprocessable Entity',
    content: new OA\JsonContent(properties: [
        new OA\Property(property: 'message', type: 'string', example: 'The given data was invalid'),
    ])
), OA\Response(
    response: 'Code429',
    description: 'Too Many Attempts',
    content: new OA\JsonContent(properties: [
        new OA\Property(property: 'message', type: 'string', example: 'Too Many Attempts'),
    ])
), OA\Response(
    response: 'Code500',
    description: 'Internal Server Error',
    content: new OA\JsonContent(properties: [
        new OA\Property(property: 'message', type: 'string', example: 'An internal server error occurred'),
    ])
)]

#[OA\Tag(name: 'auth', description: 'Guest (For Unauthenticated Users)')]
#[OA\Tag(name: 'profile', description: 'Profile (For Authenticated Users)')]
#[OA\Tag(name: 'libraries', description: 'Manage Libraries')]
#[OA\Tag(name: 'items', description: 'Manage Items of a Library')]
#[OA\Tag(name: 'posters', description: 'Upload Posters for Library Items')]
#[OA\Tag(name: 'validations', description: 'Auxiliary validation endpoints for front-end forms')]
/**
 * Base controller for API v1 routing in application
 */
abstract class ApiV1Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public const SECURITY_SCHEME_BEARER = [['BearerAuth' => []]];

    public const PARAM_LIBRARY_ID_REF = '#/components/parameters/libraryId';
    public const PARAM_ITEM_ID_REF = '#/components/parameters/itemId';
    public const PARAM_SORT_ATTR_REF = '#/components/parameters/sortAttribute';
    public const PARAM_SORT_DIR_REF = '#/components/parameters/sortDirection';
    public const PARAM_PAGE_REF = '#/components/parameters/page';
    public const PARAM_PER_PAGE_REF = '#/components/parameters/perPage';

    public const RESPONSE_204_REF = '#/components/responses/Code204';
    // public const RESPONSE_400_REF = '#/components/responses/Code400';
    public const RESPONSE_401_REF = '#/components/responses/Code401';
    public const RESPONSE_404_REF = '#/components/responses/Code404';
    public const RESPONSE_413_REF = '#/components/responses/Code413';
    public const RESPONSE_422_REF = '#/components/responses/Code422';
    public const RESPONSE_429_REF = '#/components/responses/Code429';
    public const RESPONSE_500_REF = '#/components/responses/Code500';

    public const SCHEMA_PROFILE_REF = '#/components/schemas/Profile';

    public const SCHEMA_TYPES_REF = '#/components/schemas/DataTypes';
    public const SCHEMA_LIBRARY_REF = '#/components/schemas/LibraryExample';
    public const SCHEMA_LIBRARY_ENTRY_REF = '#/components/schemas/LibraryItemExample';
    public const SCHEMA_LIBRARY_ENTRY_REQUEST_REF = '#/components/schemas/LibraryItemRequestExample';
    public const SCHEMA_LIBRARY_SEARCH_TERM_REF = '#/components/schemas/LibrarySearchTermExample';

    public const R2_STORAGE_POSTER_TMP_PREFIX = 'temp';

    #[OA\Parameter(
        parameter: 'libraryId',
        name: 'id',
        description: 'ID of an existing Library',
        in: 'path',
        required: true,
        schema: new OA\Schema(type: 'integer', example: 1),
    )]
    private string $libraryId = self::PARAM_LIBRARY_ID_REF;

    #[OA\Parameter(
        parameter: 'itemId',
        name: 'item',
        description: 'ID of an existing Item in the Library',
        in: 'path',
        required: true,
        schema: new OA\Schema(type: 'integer', example: 1),
    )]
    private string $entryId = self::PARAM_ITEM_ID_REF;

    #[OA\Parameter(
        parameter: 'sortAttribute',
        name: 'sort[attribute]',
        description: 'Sort (set sorting attribute)',
        in: 'query',
        required: false,
        schema: new OA\Schema(type: 'string', example: 'id'),
    )]
    private string $sortAttribute = self::PARAM_SORT_ATTR_REF;

    #[OA\Parameter(
        parameter: 'sortDirection',
        name: 'sort[direction]',
        description: 'Sort (set sorting direction)',
        in: 'query',
        required: false,
        schema: new OA\Schema(type: 'string', enum: ['asc', 'desc'], nullable: true),
    )]
    private string $sortDirection = self::PARAM_SORT_DIR_REF;

    #[OA\Parameter(
        parameter: 'page',
        name: 'page',
        description: 'Pagination (set current page)',
        in: 'query',
        required: false,
        schema: new OA\Schema(type: 'integer', example: 1),
    )]
    private string $page = self::PARAM_PAGE_REF;

    #[OA\Parameter(
        parameter: 'perPage',
        name: 'perPage',
        description: 'Pagination (set entries per page)',
        in: 'query',
        required: false,
        schema: new OA\Schema(type: 'integer', default: 50, enum: [0, 25, 50, 100, 250]),
    )]
    private string $perPage = self::PARAM_PER_PAGE_REF;
}
