import { type SyntheticEvent, useCallback, useEffect, useRef } from 'react';

interface CloseOnPopStateProps {
  id: string;
  open: boolean;
  onClose: (event: SyntheticEvent | PopStateEvent, reason?: string) => void;
}

/**
 * A custom hook that manages to close a modal or dialog component when the browser's back button is pressed
 * or when the history state changes, while ensuring that only the active dialog instance is affected.
 *
 * This hook integrates with the browser's history API, allowing dialogs to respond to `popstate` events
 * triggered by user interactions with the browser's navigation (e.g., pressing the back button).
 *
 * Generated by Google Gemini 2.5 Pro
 */
export const useCloseOnPopState = ({ id, open, onClose }: CloseOnPopStateProps) => {
  // Use a ref for the onClose handler to ensure the event listener always has the latest version
  // without needing to re-register it every time the parent component re-renders.
  const onCloseRef = useRef(onClose);
  useEffect(() => {
    onCloseRef.current = onClose;
  }, [onClose]);

  // This ref tracks if this specific hook instance is the "active" one corresponding to the
  // currently open dialog. This is the key to ensuring only one of the many hook instances
  // (one for each mounted dialog) manages the history at any given time.
  const isActiveRef = useRef(false);

  // This effect handles pushing and popping history states as the dialog opens and closes.
  useEffect(() => {
    if (open) {
      // When the dialog opens, it becomes the active one.
      // We push a state into the history that we can recognize later.
      isActiveRef.current = true;
      window.history.pushState({ dialogOpen: true, dialogId: id }, '');
    } else {
      // This block runs when the dialog closes (i.e., its `open` prop becomes false).
      // We only act if this instance was the one that was active.
      if (isActiveRef.current) {
        // We're no longer active.
        isActiveRef.current = false;
        // If the dialog was closed by a UI action (like ESC or a close button),
        // our history state will still be at the top of the stack. We need to pop it.
        if (window.history.state?.dialogId === id) {
          window.history.back();
        }
      }
    }
  }, [open, id]);

  // This effect sets up the listener for the 'popstate' event (e.g., browser back button).
  useEffect(() => {
    const handlePopState = (event: PopStateEvent) => {
      // The popstate event fires on ALL listeners. We only want the active one to react.
      if (isActiveRef.current) {
        // The browser back button was pressed, which means the user wants to close the dialog.
        // We set this instance to inactive and call the close handler.
        isActiveRef.current = false;
        onCloseRef.current(event, 'popstate');
      }
    };

    window.addEventListener('popstate', handlePopState);
    return () => {
      window.removeEventListener('popstate', handlePopState);
    };
  }, []); // The empty dependency array ensures this listener is added only once per hook instance.

  // The dialog component's onClose prop will be set to this.
  const onCloseWithPopstate = useCallback(
    (event: SyntheticEvent, reason?: string) => {
      // We simply call the original onClose handler provided by the component (e.g., handleClose).
      // This will change the component's state (`setOpen(false)`), which will in turn
      // trigger our `useEffect` hook above to correctly handle the history change.
      onClose(event, reason);
    },
    [onClose],
  );

  return { onCloseWithPopstate };
};
